### ISSUE TITLE
bug: GitHub anchor tag has incorrect href. 

### ISSUE THREAD

**Issue by xdotli** [zhizhengwu/zhizhengwu.github.io#1]
The GitHub icon on the social media list is 
```
<a href="https://github.com/https://github.com/zhizhengwu">
  <i class="fab fa-fw fa-github" aria-hidden="true"></i> Github
</a>
```
`href` in anchor should be "https://github.com/zhizhengwu".

**Comment by zhizhengwu** [comment]
done. Fixed now. Thanks for reporting. I was not aware of that :)
